export const tshirt = [
  
  {
  collec :"frite cola electrique",
  name:"T-shirt frite cola electrique",
  comment:"Le t-shirt officiel du groupe",
  img:"logoT",
  price:"50$",
},
{
  collec :"",
  name:"T-shirt frite cola electrique lp",
  comment:"Le t-shirt officiel de l'album",
  img:"coverlp",
  price:"50$",
},
{
  collec :"",
  name:"T-shirt tous ensemble 1",
  comment:"brossage de dent collectif",
  img:"dent",
  price:"50$",
},
{
  collec :"",
  name:"T-shirt tous ensemble 2",
  comment:"tous ensemble!",
  img:"Tous",
  price:"50$",
},
{
  collec :"",
  name:"T-shirt Chris Face",
  comment:"Le t-shirt du plus sexy des leader",
  img:"face1",
  price:"35$",
},
  {
  collec :"",
  name:"T-shirt David Face",
  comment:"Protège toi du soleil",
  img:"face2",
  price:"35$",
},
{
  collec :"",
  name:"T-shirt Mae Face",
  comment:"mais tu ma fait peur!",
  img:"face3",
  price:"35$",
},
{
  collec :"",
  name:"T-shirt Randy Face",
  comment:"I feel like a cowboy",
  img:"face4",
  price:"35$",
},
  {
  collec :"",
  name:"T-shirt Tony Face",
  comment:"Uhh!? ugahuhuu!",
  img:"face5",
  price:"35$",
},
{
  collec :"",
  name:"T-shirt rebelles",
  comment:"On est des rebelles! ok!!",
  img:"cadi",
  price:"30$",
},
{
  collec :"",
  name:"T-shirt young Mae",
  comment:"young and jolie",
  img:"maejeune",
  price:"40$",
},
  {
  collec :"",
  name:"T-shirt young Tony",
  comment:"Young and puceau",
  img:"tonyjeune",
  price:"40$",
},
{
  collec :"",
  name:"T-shirt young Chris",
  comment:"Young and alcoolique",
  img:"chrisbiere",
  price:"40$",
},
{
  collec :"",
  name:"T-shirt Mac Donalds 1",
  comment:"fucked up as fuck",
  img:"mac",
  price:"30$",
},
  {
  collec :"",
  name:"T-shirt Mac Donalds 2",
  comment:"very fucked up as fuck",
  img:"mac2",
  price:"30$",
},
{
  collec :"",
  name:"T-shirt Mac Donalds 3",
  comment:"travail petite!",
  img:"maemac",
  price:"30$",
},
{
  collec :"",
  name:"T-shirt costume 1",
  comment:"Jesus multiplia les pintes",
  img:"jesus",
  price:"35$",
},
  {
  collec :"",
  name:"T-shirt costume 2",
  comment:"il y a t'il une hotesse dans l'appareil?",
  img:"maehot",
  price:"35$",
},
{
  collec :"",
  name:"T-shirt costume 3",
  comment:"j'ai la coupe qui te chamboule",
  img:"tonyveuch",
  price:"35$",
},
{
  collec :"",
  name:"T-shirt pépère 1",
  comment:"on est pas bien la? décontracté du gland",
  img:"chrispepere",
  price:"25$",
},
  {
  collec :"",
  name:"T-shirt pépère 2",
  comment:"pépère le chat!",
  img:"randypepere",
  price:"25$",
},
{
  collec :"",
  name:"T-shirt pépère 3",
  comment:"ventre plein, homme serein",
  img:"randypepere2",
  price:"25$",
},
{
  collec :"",
  name:"T-shirt fatigance",
  comment:"zzzzzzzzz",
  img:"chrisdog",
  price:"30$",
},
{
  collec :"",
  name:"T-shirt gueule de bois",
  comment:"zzzzz, je suis defuuu,zzzzz!",
  img:"chrisdort",
  price:"30$",
},
{
  collec :"",
  name:"T-shirt on the top of the world",
  comment:"je veux pas me la pété mais...",
  img:"maetoit",
  price:"25$",
},
{
  collec :"",
  name:"T-shirt la bière ou la vie",
  comment:"j'mmee casse la guueuulle!",
  img:"skate",
  price:"40$",
},
{
  collec :"",
  name:"T-shirt happy",
  comment:"A table!",
  img:"randysmile",
  price:"50$",
},
{
  collec :"",
  name:"T-shirt bizarre",
  comment:"uughh!argu!!",
  img:"tonybizar",
  price:"45$",
},

{
  collec :"",
  name:"20 préservatifs hosted by Chris",
  comment:"pour 48 heures de bonheur",
  img:"capote",
  price:"45$",
},


]